### PR TITLE
Manual connect/disconnect feature added

### PR DESCRIPTION
**Pull request by f4l0**
- AutoGate entry added to X-Plane menu
- Manual connect/disconnect feature added

### CODE REVIEW

**Comment by Marginal** [comment]
I can't review this patch. Please force push a *minimal* patch. You may have to fix your git line endings settings.

**Comment by f4l0** [comment]
Ah, I see that the diff for autogate.h covers the whole file...

**Comment by f4l0** [comment]
I'll file a new pull request

**Comment by f4l0** [comment]
Hmm... still some issues. I configured my Windows cygwin client as described in https://help.github.com/articles/dealing-with-line-endings/

I'll check this stuff at my Linux box later...

**Pull request closed without merging**
